version: "3"
services:
  # music-market:
  #   build:
  #     context: ./backend
  #   restart: always
  #   env_file:
  #     - .env
  #   ports:
  #     - 3000:3000
  #   container_name: music-market
  #   # depends_on:
  #   #   - postgres
  #   networks:
  #     - app-network

  # webserver:
  #   image: nginx:mainline-alpine
  #   container_name: webserver
  #   restart: unless-stopped
  #   ports:
  #     - "80:80"
  #     - "443:443"
  #   volumes:
  #     - web-root:/var/www/html
  #     - ./nginx-conf:/etc/nginx/conf.d
  #     - certbot-etc:/etc/letsencrypt
  #     - certbot-var:/var/lib/letsencrypt
  #     - dhparam:/etc/ssl/certs
  #   depends_on:
  #     - music-market
  #   networks:
  #     - app-network

  # certbot:
  #   image: certbot/certbot
  #   container_name: certbot
  #   volumes:
  #     - certbot-etc:/etc/letsencrypt
  #     - certbot-var:/var/lib/letsencrypt
  #     - web-root:/var/www/html
  #   depends_on:
  #     - webserver
  #   command: certonly --webroot --webroot-path=/var/www/html --email yana@digiwaymedia.com --agree-tos --no-eff-email --force-renewal -d api.digiwaysite.tech

  # admin:
  #   build:
  #     context: ./admin
  #   restart: always
  #   env_file:
  #     - ./admin/.env
  #   ports:
  #     - 3001:3001
  #   # depends_on:
  #   #   - postgres
  #   networks:
  #     - app-network
  # postgres:
  #   image: postgres:12-alpine
  #   hostname: postgres
  #   container_name: postgres
  #   env_file:
  #     - .env
  #   volumes:
  #     - ./.data/postgresql:/var/lib/postgresql/data
  #   environment:
  #     POSTGRES_PASSWORD: $DB_PASS
  #     POSTGRES_USER: $DB_USER
  #     POSTGRES_DB: $DB_NAME
  #   restart: always
  #   ports:
  #     - $DB_OUTER_PORT:$DB_INNER_PORT
  #   networks:
  #     - app-network

  adminer:
    image: adminer
    restart: always
    # depends_on:
    #   - postgres
    ports:
      - 8081:8080
  # volumes:
  # certbot-etc:
  # certbot-var:
  # web-root:
  #   driver: local
  #   driver_opts:
  #     type: none
  #     device: /home/ec2-user/music-market/views/
  #     o: bind
  # dhparam:
  #   driver: local
  #   driver_opts:
  #     type: none
  #     device: /home/ec2-user/music-market/dhparam/
  #     o: bind

networks:
  app-network:
    driver: bridge
