export const SEQUELIZE = 'SEQUELIZE';
export const DEVELOPMENT = 'development';
export const TEST = 'test';
export const PRODUCTION = 'production';

export const USER_REPOSITORY = 'USER_REPOSITORY';
export const RESET_PASSWORD_REPOSITORY = 'RESET_PASSWORD_REPOSITORY';
export const CATEGORY_REPOSITORY = 'CATEGORY_REPOSITORY';
export const INSTRUMENTS_REPOSITORY = 'INSTRUMENTS_REPOSITORY';
export const MOODS_REPOSITORY = 'MOODS_REPOSITORY';
export const KEYS_REPOSITORY = 'KEYS_REPOSITORY';
export const MUSICS_REPOSITORY = 'MUSICS_REPOSITORY';
export const PLAYLIST_MUSICS_REPOSITORY = 'PLAYLIST_MUSICS_REPOSITORY';
export const TRACK_TYPES_REPOSITORY = 'TRACK_TYPES_REPOSITORY';
export const MUSIC_CATEGORIES_REPOSITORY = 'MUSIC_CATEGORIES_REPOSITORY';
export const MUSIC_INSTRUMENTS_REPOSITORY = 'MUSIC_INSTRUMENTS_REPOSITORY';
export const MUSIC_MOODS_REPOSITORY = 'MUSIC_MOODS_REPOSITORY';
export const MUSIC_KEYS_REPOSITORY = 'MUSIC_KEYS_REPOSITORY';
export const MUSIC_TYPES_REPOSITORY = 'MUSIC_TYPES_REPOSITORY';
export const MUSIC_HISTORY_REPOSITORY = 'MUSIC_HISTORY_REPOSITORY';
export const MUSIC_FAVORITES_REPOSITORY = 'MUSIC_FAVORITES_REPOSITORY';
export const MUSIC_COMMENTS_REPOSITORY = 'MUSIC_COMMENTS_REPOSITORY';
export const MUSIC_FILES_REPOSITORY = 'MUSIC_FILES_REPOSITORY';
export const FOLLOW_REPOSITORY = 'FOLLOW_REPOSITORY';
export const CART_REPOSITORY = 'CART_REPOSITORY';
export const TRANSACTION_REPOSITORY = 'TRANSACTION_REPOSITORY';
export const SALES_REPOSITORY = 'SALES_REPOSITORY';
export const WITHDRAWAL_REPOSITORY = 'WITHDRAWAL_REPOSITORY';
export const BILLING_ADDRESS_REPOSITORY = 'BILLING_ADDRESS_REPOSITORY';
export const PAYOUT_REPOSITORY = 'PAYOUT_REPOSITORY';
export const REPORTS_REPOSITORY = 'REPORTS_REPOSITORY';
export const SETTINGS_REPOSITORY = 'SETTINGS_REPOSITORY';
export const NOTIFICATION_REPOSITORY = 'NOTIFICATION_REPOSITORY';
export const HELP_REQUEST_REPOSITORY = 'HELP_REQUEST_REPOSITORY';
export const CONTENT_REPOSITORY = 'CONTENT_REPOSITORY';
export const MEDIA_CONTENT_REPOSITORY = 'MEDIA_CONTENT_REPOSITORY';
export const INNER_TRANSACTIONS_REPOSITORY = 'INNER_TRANSACTIONS_REPOSITORY';
export const PLAYLIST_REPOSITORY = 'PLAYLIST_REPOSITORY';
export const PLAYLIST_FOLLOWS_REPOSITORY = 'PLAYLIST_FOLLOWS_REPOSITORY';
export const HELP_REPOSITORY = 'HELP_REPOSITORY';

export const API_NAMES_LIST = [
  'auth',
  'users',
  'categories',
  'instrument',
  'moods',
  'keys',
  'musics',
  'types',
  'cart',
  'transaction',
  'sales',
  'withdrawal',
  'billing-address',
  'payout',
  'subscription',
  'cards',
  'reports',
  'settings',
  'notifications',
  'content',
];
